name: Murder
author: peptiGamer
version: 0.9
api: [3.0.0, 3.1.0, 3.8.2]
main: TheNewHEROBRINE\Murder\MurderMain
load: POSTWORLD

permissions:
 murder:
  children:
   murder.command:
    children:
     murder.command.join:
      default: true
     murder.command.quit:
      default: true
     murder.command.setarena:
      default: op
